//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Boolean p_main_Teleport;
        
        private static SteamVR_Action_Boolean p_main_Grab;
        
        private static SteamVR_Action_Pose p_main_Pose;
        
        private static SteamVR_Action_Boolean p_main_Capture;
        
        private static SteamVR_Action_Vibration p_main_Haptic;
        
        public static SteamVR_Action_Boolean main_Teleport
        {
            get
            {
                return SteamVR_Actions.p_main_Teleport.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Boolean main_Grab
        {
            get
            {
                return SteamVR_Actions.p_main_Grab.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Pose main_Pose
        {
            get
            {
                return SteamVR_Actions.p_main_Pose.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        public static SteamVR_Action_Boolean main_Capture
        {
            get
            {
                return SteamVR_Actions.p_main_Capture.GetCopy<SteamVR_Action_Boolean>();
            }
        }
        
        public static SteamVR_Action_Vibration main_Haptic
        {
            get
            {
                return SteamVR_Actions.p_main_Haptic.GetCopy<SteamVR_Action_Vibration>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.main_Teleport,
                    SteamVR_Actions.main_Grab,
                    SteamVR_Actions.main_Pose,
                    SteamVR_Actions.main_Capture,
                    SteamVR_Actions.main_Haptic};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.main_Teleport,
                    SteamVR_Actions.main_Grab,
                    SteamVR_Actions.main_Pose,
                    SteamVR_Actions.main_Capture};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[] {
                    SteamVR_Actions.main_Haptic};
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[] {
                    SteamVR_Actions.main_Haptic};
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.main_Pose};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[] {
                    SteamVR_Actions.main_Teleport,
                    SteamVR_Actions.main_Grab,
                    SteamVR_Actions.main_Capture};
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[0];
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[0];
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.main_Teleport,
                    SteamVR_Actions.main_Grab,
                    SteamVR_Actions.main_Capture};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_main_Teleport = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Main/in/Teleport")));
            SteamVR_Actions.p_main_Grab = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Main/in/Grab")));
            SteamVR_Actions.p_main_Pose = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/Main/in/Pose")));
            SteamVR_Actions.p_main_Capture = ((SteamVR_Action_Boolean)(SteamVR_Action.Create<SteamVR_Action_Boolean>("/actions/Main/in/Capture")));
            SteamVR_Actions.p_main_Haptic = ((SteamVR_Action_Vibration)(SteamVR_Action.Create<SteamVR_Action_Vibration>("/actions/Main/out/Haptic")));
        }
    }
}
